spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: project-service
          uri: ${PROJECT_ROUTE_URI:http://localhost:8083/}
          predicates:
            - Path=/projects/**

        - id: task-service
          uri: ${TASK_ROUTE_URI:http://localhost:8082/}
          predicates:
            - Path=/api/v1/task/**

        - id: Report-Service
          uri: ${REPORT_ROUTE_URI:http://localhost:8084/}
          predicates:
            - Path=/api/v1/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
