spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/v1/task/**
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/projects/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/v1/report/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
